# Config for workstyle
#
# Format:
# "pattern" = "icon"
#
# "pattern" must be lowercase
#
# The pattern will be used to match against the application name, class_id or WM_CLASS.
# The icon will be used to represent that application.
#
# Note if multiple patterns are present in the same application name,
# precedence is given in order of apparition in this file.

"kitty" = "ï„ "
"alacritty" = "ï„ "

"google" = "ï† "
"private browsing" = "ïˆ›"
"firefox" = "ï‰©"
"chrome" = "ï‰¨"

"file manager" = "ï¼"
"dolphin" = "ï¼"
"thunar" = "ï¼"

"github" = "ï„“"
"rust" = "î¨"
"nvim" = "îŸ…"
"codium" = "ó°¨"
"code-oss" = "ó°¨"


"qbittorrent" = "î¯‹"
"wireshark" = "ó±™³"

"virt-manager" = "î©º"
"remmina" = "ó°¢¹"

"blender" = "î¦"
"gimp" = "ïŒ¸"

"discord" = "ï‡¿"
"steam" = "ï†¶"

"keepassxc" = "ï‚„"

"gthumb" = "ï€¾"
"feh" = "ï€¾"
"menu" = "ï¡œ"
"calculator" = "ï—«"
"transmission" = "ï€™"
"videostream" = "ï˜˜"
"mpv" = "ïœª"
"music" = "ï€"
"disk usage" = "ïŸ‰"
".pdf" = "ïœ¤"

[other]
fallback_icon = "ğŸ¤¨"
deduplicate_icons = true 
separator = ": "
